services:
  - type: web
    name: kenylson-portfolio
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: kenylson-portfolio-disk
      mountPath: /opt/render/project/src
      sizeGB: 1